# Generated by Django 5.0.7 on 2026-04-17 03:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('emoji', models.CharField(default='📦', max_length=10, verbose_name='Emoji')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'ddp_modules',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=25, verbose_name='Téléphone')),
                ('telephone2', models.CharField(blank=True, max_length=25, verbose_name='Téléphone 2 (optionnel)')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville de résidence')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, verbose_name='Situation matrimoniale')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('role', models.CharField(choices=[('caissiere', 'Caissière'), ('comptable', 'Comptable'), ('directrice', 'Directrice'), ('super_admin', 'Super Administrateur')], max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Django')),
                ('mot_de_passe_provisoire', models.BooleanField(default=True, verbose_name='Mot de passe provisoire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('modules_autorises', models.ManyToManyField(blank=True, related_name='utilisateurs', to='authentication.module', verbose_name='Modules autorisés')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'ddp_users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('echec_connexion', 'Échec de connexion'), ('creation_user', 'Création utilisateur'), ('modification_user', 'Modification utilisateur'), ('desactivation_user', 'Désactivation utilisateur'), ('modification_permissions', 'Modification des permissions'), ('ouverture_caisse', 'Ouverture de caisse'), ('fermeture_caisse', 'Fermeture de caisse'), ('validation_versement', 'Validation versement'), ('enregistrement_patient', 'Enregistrement patient'), ('modification_fiche', 'Modification fiche paiement')], max_length=50, verbose_name='Action')),
                ('details', models.JSONField(default=dict, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'ddp_audit_logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='PermissionGranulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom lisible')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_granulaires', to='authentication.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Permission granulaire',
                'verbose_name_plural': 'Permissions granulaires',
                'db_table': 'ddp_permissions_granulaires',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='permissions_granulaires',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='authentication.permissiongranulaire', verbose_name='Permissions granulaires'),
        ),
    ]
