# Generated by Django 5.0.7 on 2026-04-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_secondaire',
            field=models.CharField(blank=True, choices=[('caissiere', 'Caissière'), ('comptable', 'Comptable'), ('directrice', 'Directrice'), ('super_admin', 'Super Administrateur')], max_length=20, null=True, verbose_name='Rôle secondaire (optionnel)'),
        ),
    ]
