# Generated by Django 5.0.7 on 2026-04-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role_secondaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_secondaire',
        ),
        migrations.AddField(
            model_name='user',
            name='roles_supplementaires',
            field=models.JSONField(blank=True, default=list, verbose_name='Rôles supplémentaires'),
        ),
    ]
