# Generated by Django 5.0.7 on 2026-04-15 03:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ouverte_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ouverture")),
                ('date_session', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='Date')),
                ('fermee_le', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('montant_systeme', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant système (calculé)')),
                ('montant_compte', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant compté (caissière)')),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Écart')),
                ('justificatif_caissiere', models.TextField(blank=True, verbose_name='Justificatif caissière')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('montant_recu_comptable', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant reçu (comptable)')),
                ('ecart_comptable', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Écart côté comptable')),
                ('note_comptable', models.TextField(blank=True, verbose_name='Note comptable')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_attente', 'En attente de validation'), ('validee', 'Validée')], default='ouverte', max_length=20, verbose_name='Statut')),
                ('ouverte_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_ouvertes', to=settings.AUTH_USER_MODEL, verbose_name='Ouverte par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'db_table': 'ddp_sessions_caisse',
                'ordering': ['-date_session'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_dossier', models.CharField(max_length=20, unique=True, verbose_name='Numéro de dossier')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('domicile', models.CharField(blank=True, max_length=200, verbose_name='Domicile')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], default='M', max_length=1, verbose_name='Sexe')),
                ('a_assurance', models.BooleanField(default=False, verbose_name='Assuré')),
                ('numero_assurance', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'assurance")),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='configuration.assurance', verbose_name='Assurance')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='caisse.sessioncaisse', verbose_name='Session de caisse')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'ddp_patients',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='FichePaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('quantite', models.PositiveSmallIntegerField(default=1, verbose_name='Quantité')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('taux_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux assurance (%)')),
                ('montant_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant assurance')),
                ('montant_patient', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant patient')),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('assurance', 'Prise en charge assurance')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('creee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_paiement', to='configuration.prestation', verbose_name='Prestation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiches_paiement', to='configuration.service', verbose_name='Service')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_paiement', to='caisse.patient', verbose_name='Patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_paiement', to='caisse.sessioncaisse', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Fiche de paiement',
                'verbose_name_plural': 'Fiches de paiement',
                'db_table': 'ddp_fiches_paiement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
