# Generated by Django 5.0.7 on 2026-04-16 04:32

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncaisse',
            name='heure_fin_prevue',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin prévue'),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='date_session',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
        migrations.AlterUniqueTogether(
            name='sessioncaisse',
            unique_together={('ouverte_par', 'date_session')},
        ),
    ]
