# Generated by Django 5.0.7 on 2026-04-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_sessioncaisse_heure_fin_prevue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepaiement',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiches_paiement', to='caisse.sessioncaisse', verbose_name='Session de validation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='caisse.sessioncaisse', verbose_name='Session de caisse'),
        ),
    ]
