# Generated by Django 5.0.7 on 2026-04-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_fichepaiement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepaiement',
            name='reference',
            field=models.CharField(blank=True, help_text='Numéro unique retrouvable dans le dossier patient. Ex: FICHE-2026-A3B9F12C', max_length=30, unique=True, verbose_name='Référence du reçu'),
        ),
    ]
