# Generated by Django 5.0.7 on 2026-04-15 03:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('taux_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de prise en charge par défaut (%)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
                'db_table': 'ddp_assurances',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ParametresClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Ma Clinique', max_length=200, verbose_name='Nom')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinique/', verbose_name='Logo')),
                ('monnaie', models.CharField(default='FCFA', max_length=10, verbose_name='Monnaie')),
                ('informations_legales', models.TextField(blank=True, verbose_name='Informations légales')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres clinique',
                'db_table': 'ddp_parametres_clinique',
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Libellé')),
                ('emoji', models.CharField(default='🩺', max_length=10, verbose_name='Emoji')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (FCFA)')),
                ('prise_en_charge_assurance', models.BooleanField(default=False, verbose_name='Prise en charge assurance')),
                ('taux_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux assurance (%)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'db_table': 'ddp_prestations',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du service')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'ddp_services',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
