# Generated by Django 5.0.7 on 2026-04-17 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurance',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='prestation',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='prestation',
            name='taux_assurance',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='assurance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations', to='configuration.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='taux_defaut',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5, verbose_name='Taux par défaut (%)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
